# Generated by Django 5.2.2 on 2025-06-05 09:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_registro', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Número de Registro')),
                ('marca', models.CharField(help_text='Ex: Fiat, Chevrolet, Volkswagen', max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo do Veículo')),
                ('placa', models.CharField(max_length=10, unique=True, verbose_name='Placa')),
                ('chassi', models.CharField(max_length=17, unique=True, verbose_name='Chassi')),
                ('renavam', models.CharField(max_length=11, unique=True, verbose_name='Renavam')),
                ('ano_fabricacao', models.IntegerField(verbose_name='Ano de Fabricação')),
                ('ano_modelo', models.IntegerField(verbose_name='Ano do Modelo')),
                ('zero_kilometro', models.BooleanField(default=False, verbose_name='Zero Quilômetro')),
                ('nome_condutor', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome do Condutor')),
                ('classe_bonus', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=0, verbose_name='Classe de Bônus')),
                ('seguradora', models.CharField(help_text='Ex: Porto Seguro, Tokio Marine, Azul Seguros', max_length=100, verbose_name='Seguradora')),
                ('franquia', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Franquia')),
                ('data_vencimento_seguro', models.DateField(verbose_name='Data de Vencimento do Seguro')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro no Sistema')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo no Sistema')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculos', to='veiculos.empresa', verbose_name='Empresa Proprietária')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'ordering': ['placa'],
            },
        ),
    ]
