# Generated by Django 5.2.2 on 2025-06-05 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('veiculos', '0002_veiculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sinistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_sinistro', models.DateField(verbose_name='Data do Sinistro')),
                ('tipo_sinistro', models.CharField(choices=[('colisao', 'Colisão'), ('roubo', 'Roubo'), ('furto', 'Furto'), ('incendio', 'Incêndio'), ('danos_terceiros', 'Danos a Terceiros'), ('fenomeno_natureza', 'Fenômeno da Natureza'), ('outros', 'Outros')], default='colisao', max_length=50, verbose_name='Tipo de Sinistro')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição Detalhada')),
                ('status_sinistro', models.CharField(choices=[('em_analise', 'Em Análise'), ('aberto', 'Aberto'), ('concluido_com_indenizacao', 'Concluído com Indenização'), ('concluido_sem_indenizacao', 'Concluído sem Indenização'), ('negado', 'Negado'), ('cancelado', 'Cancelado')], default='em_analise', max_length=50, verbose_name='Status do Sinistro')),
                ('data_registro_sistema', models.DateTimeField(auto_now_add=True, verbose_name='Data de Registro no Sistema')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sinistros', to='veiculos.veiculo', verbose_name='Veículo Sinistrado')),
            ],
            options={
                'verbose_name': 'Sinistro',
                'verbose_name_plural': 'Sinistros',
                'ordering': ['-data_sinistro', 'veiculo__placa'],
            },
        ),
    ]
